! This file is part of cuckoohash.
! SPDX-Identifier: Apache-2.0

!> Tester for the cuckoo hash map implementation
program test_cuckoohash
   use testdrive
   use map_cuckoohash
   implicit none

   type(cuckoo_hash) :: map
   type(container_type), pointer :: view
   type(error_type), allocatable :: error

   call new_cuckoo_hash(map, 10)
   call check(error, len(map), 0)

   call map%get("tight-binding", view)
   call check(error, .not.associated(view))

   call map%insert("tight-binding", view)
   call check(error, associated(view))
   call check(error, len(map), 1)

   call map%insert("semi-empirics", view)
   call map%insert("semi-empirics", view)
   call map%insert("quantum-mechanics", view)
   call check(error, len(map), 3)

   call map%drop("tight-binding")
   call check(error, len(map), 2)

   call map%insert("talkative-backs", view)
   call map%insert("thick-bounces", view)
   call map%insert("tubby-broadcast", view)
   call map%insert("these-bump", view)
   call map%insert("tricky-broadcast", view)
   call map%insert("thick-brush", view)
   call map%insert("tart-brushes", view)
   call map%insert("tragic-box", view)
   call map%insert("thankful-bail", view)
   call map%insert("trustworthy-balloon", view)
   call map%insert("tame-balances", view)
   call map%insert("tight-bumps", view)
   call map%insert("tangible-bump", view)
   call map%insert("tart-bother", view)
   call map%insert("trivial-balloons", view)
   call map%insert("twin-break", view)
   call map%insert("tall-bandage", view)
   call map%insert("twin-boxes", view)
   call map%insert("tense-bounce", view)
   call map%insert("thunderous-blast", view)
   call map%insert("trivial-backs", view)
   call map%insert("twin-board", view)
   call map%insert("tremendous-benefits", view)
   call map%insert("trained-breaks", view)
   call map%insert("thorny-bank", view)
   call map%insert("traumatic-bounces", view)
   call map%insert("traumatic-bank", view)
   call map%insert("thankful-bargain", view)

   call map%get("tight-binding", view)
   call check(error, .not.associated(view))
   call map%get("semi-empirics", view)
   call check(error, associated(view))
   call map%get("quantum-mechanics", view)
   call check(error, associated(view))
   call map%get("talkative-backs", view)
   call check(error, associated(view))
   call map%get("thick-bounces", view)
   call check(error, associated(view))
   call map%get("tubby-broadcast", view)
   call check(error, associated(view))
   call map%get("these-bump", view)
   call check(error, associated(view))
   call map%get("tricky-broadcast", view)
   call check(error, associated(view))
   call map%get("thick-brush", view)
   call check(error, associated(view))
   call map%get("tart-brushes", view)
   call check(error, associated(view))
   call map%get("tragic-box", view)
   call check(error, associated(view))
   call map%get("thankful-bail", view)
   call check(error, associated(view))
   call map%get("trustworthy-balloon", view)
   call check(error, associated(view))
   call map%get("tame-balances", view)
   call check(error, associated(view))
   call map%get("tight-bumps", view)
   call check(error, associated(view))
   call map%get("tangible-bump", view)
   call check(error, associated(view))
   call map%get("tart-bother", view)
   call check(error, associated(view))
   call map%get("trivial-balloons", view)
   call check(error, associated(view))
   call map%get("twin-break", view)
   call check(error, associated(view))
   call map%get("tall-bandage", view)
   call check(error, associated(view))
   call map%get("twin-boxes", view)
   call check(error, associated(view))
   call map%get("tense-bounce", view)
   call check(error, associated(view))
   call map%get("thunderous-blast", view)
   call check(error, associated(view))
   call map%get("trivial-backs", view)
   call check(error, associated(view))
   call map%get("twin-board", view)
   call check(error, associated(view))
   call map%get("tremendous-benefits", view)
   call check(error, associated(view))
   call map%get("trained-breaks", view)
   call check(error, associated(view))
   call map%get("thorny-bank", view)
   call check(error, associated(view))
   call map%get("traumatic-bounces", view)
   call check(error, associated(view))
   call map%get("traumatic-bank", view)
   call check(error, associated(view))
   call map%get("thankful-bargain", view)
   call check(error, associated(view))

   call map%clear
   call check(error, len(map), 0)

end program test_cuckoohash
